type Vod {
  id: ObjectID!
  user_id: ObjectID!
  title: String!
  categories: [VodCategory!]!
  state: VodState!
  visibility: VodVisibility!
  variants: [VodVariant!]!
  started_at: Time!
  ended_at: Time
  thumbnails: VodThumbnails!

  user: User! @goField(forceResolver: true)
}

type VodThumbnails {
  static: String!
  animated: String!
}

type VodCategory {
  timestamp: Time!
  name: String!
  id: String!
  url: String!
}

type VodVariant {
  name: String!
  width: Int!
  height: Int!
  fps: Int!
  bitrate: Int!
  ready: Boolean!
}

enum VodState {
  Live
  Queued
  Processing
  Ready
  Storage
  Failed
  Canceled
}

enum VodVisibility {
  Public
  Deleted
}

extend type Query {
  vod(id: ObjectID!): Vod
  vods(
    user_id: ObjectID!
    limit: Int!
    page: Int!
    search: String
    after: Time
    before: Time
  ): [Vod!]
}
